### PR TITLE
fix for jira ESBJAVA-4139

### PR DESCRIPTION
**Pull request by vanii**

### CODE REVIEW

**Comment by callkalpa** [comment]
Hi @vanii ,

We need to have a Carbon JIRA for this and the fix needs to be verified by the team lead.

**Comment by callkalpa** [comment]
Hi @vanii,

Do we still need this fix to go into the next minor release?

**Comment by Nipuni** [comment]
Hi Vanii,

Can we get this reviewed by the team lead if this is to go to the next patch release?

**Comment by Kishanthan** [comment]
@bsenduran , please review and merge this as this seems to be used at EI product.

**Comment by bsenduran** [comment]
Closing since this introduces the requirement to have knowledge of a .jsp page specifically used in EI inside carbon-deployment

**Pull request closed without merging**
